<a href="https://colab.research.google.com/github/hongrolee/Python-Basic/blob/main/colab/%ED%8C%8C%EC%9D%B4%EC%8D%AC%20%EC%A4%91%EA%B8%89-numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 기초

## Numpy 개념

* Numerical Python의 약자
* 파이썬에서 배열 처리에 유용한 라이브러리
* 배열 계산에 최적화된 방식과 빠른 처리 속도를 자랑함



## Numpy 특징

* 처리 속도가 빠르며, 유연한 연산 제공
* 배열 내용을 한번에 디스크에 저장 및 불러오기 기능 제공
* C/C++로 작성한 코드와 연결 가능
* pandas, OpenCV 등 유명한 라이브러리가 numpy를 기반으로 작성



## Numpy 설치
- pip install numpy

In [2]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


## import

In [3]:
import numpy as np

## 생성

*   np.array() : 리스트를 넘파이 배열로 변환
*   np.arange() : 연속된 값 생성, range와 유사
*   np.one() : 1로 구성된 배열 생성
*   np.zeros() : 0으로 구성된 배열 생성
*   np.empty() : 빈 배열 생성(쓰레기값 포함)
*   np.full() : 배열 생성시 파라미터 값으로 초기화
*   np.identity() : 단위행렬 생성(대각선이 1로 채워짐)
*   np.random.randint() : 임의의 정수값으로 생성, randint(0,255,size=(2,3))
*   np.random.rand() : 임의의 실수값으로 생성(0~0.9999)

*   생성시, 데이터 타입 지정 가능 : 예> dtype=np.float32
 - int8 ~ int64 : 부호있는 정수형
 - uint8 ~ uint64 : 부호없는 정수형
 - float16 ~ float128 : 부동 소수점
 - bool : True 또는 False
 - string_ : 영문 문자열
 - unicode_ : 한글을 포함한 기타 언어 문자열

*   데이터 정보 확인 : 예>array.dtype
 - dtype : 데이터 타입
 - ndim : 배열의 차원
 - shape : 배열의 크기




In [51]:
list = [1,2,3,4,5]
# print(list)
# print(np.array(list))

# print(np.arange(0,100,10))
# print(np.ones((10,10))
# print(np.zeros((10,10)))
# print(np.empty((10,10)))
# print(np.full(5,33))
# print(np.identity(10))
print(np.random.randint(0,255,size=(2,3)))
# print(np.random.rand(10))

# print(np.ones((10,10),dtype=np.float16))

[[241  69  59]
 [ 80 174  71]]


## 삽입
*   리스트와 동일
*   인덱스 활용



In [62]:
array = np.arange(5,10,1)
print(array)
array[0] = 100
print(array)

[5 6 7 8 9]
[100   6   7   8   9]


## 슬라이싱

# 유용한 함수

## reshape()
- 1차원 배열을 2차원으로 변경 또는 2차원 배열을 1차원 배열로 변경

*   1차원 -> 2차원 : reshape(행,열)
*   2차원 -> 1차원 : reshape(크기)

